### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by rsheasby** [ben-sb/javascript-deobfuscator#15]
Hi!

I'm attempting to use this to deobfuscate a relatively big javascript bundle (about 3mb minified), and am running into quite a few issues with it running out of memory. I've increased the stack size to 65500 using `--stack-size=65500` (I also updated the ulimit appropriately), and have increased the max memory usage to 30000 MB using `--max-old-space-size=30000`, but still am running into issues. The most recent attempt had the following error when it reached about 18GB of memory usage (there was enough available memory on the host):
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

I also saw some high cpu usage for python while it was crashing, not sure if there's a python component of this tool?

The high memory usage is during the "remove proxy functions" stage. Any ideas of places that can be further optimised to work better for big inputs?

**Comment by rsheasby** [comment]
Unfortunately the source is proprietary and I'm not able to share it 😢 

Any ideas how I might be able to profile it myself to figure out the issue?
Is it possible that there's two proxy functions calling each other and they're getting resolved in a loop? Almost like a symlink loop. I see the proxy remover seems to be recursive, so maybe that could be why it's running out of memory?

**Comment by ben-sb** [comment]
I've made some minor efficiency improvements to proxy function searching in 222f250dd09879f66a8314848eeabd1fbc54d293 however without access to a sample I doubt I'll be able to find the exact cause.

As for finding the issue yourself you could either use the debugger/inspector to see what's using up too much memory, or follow the flow of the code in src/modifications/proxies/proxyRemover.ts and see which stage it hits the memory limit at.

Two proxy functions calling itself is actually a good point as that does cause an error, however it's a range error (RangeError: Maximum call stack size exceeded) so that's probably not the issue in your case. I'll also look into detecting and avoiding infinite loops.

**Comment by rsheasby** [comment]
As a matter of fact that RangeError is exactly what I get if I don't increase the stack size and max memory. I suspect the call loop is exactly what's happening. Any possibility of handling that error yourself and gracefully aborting functions that cause a stack error, while continuing with the remainder of the code?

**Comment by rsheasby** [comment]
Aha, we're making progress. I think this is probably solved tbh. At this point I just need to fiddle with the function executor to get my output usable.
